/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface IdesoftCopyright {
    }
}
declare global {
    interface HTMLIdesoftCopyrightElement extends Components.IdesoftCopyright, HTMLStencilElement {
    }
    var HTMLIdesoftCopyrightElement: {
        prototype: HTMLIdesoftCopyrightElement;
        new (): HTMLIdesoftCopyrightElement;
    };
    interface HTMLElementTagNameMap {
        "idesoft-copyright": HTMLIdesoftCopyrightElement;
    }
}
declare namespace LocalJSX {
    interface IdesoftCopyright {
    }
    interface IntrinsicElements {
        "idesoft-copyright": IdesoftCopyright;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "idesoft-copyright": LocalJSX.IdesoftCopyright & JSXBase.HTMLAttributes<HTMLIdesoftCopyrightElement>;
        }
    }
}
